// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_room_ from "./routes/[room].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_guess from "./routes/api/guess.ts";
import * as $api_rooms_index from "./routes/api/rooms/index.ts";
import * as $api_sendMessage from "./routes/api/sendMessage.ts";
import * as $api_supabase_textToImage from "./routes/api/supabase/textToImage.ts";
import * as $index from "./routes/index.tsx";
import * as $Clipboard from "./islands/Clipboard.tsx";
import * as $Game from "./islands/Game.tsx";
import * as $Lobby from "./islands/Lobby.tsx";
import * as $Share from "./islands/Share.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[room].tsx": $_room_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/guess.ts": $api_guess,
    "./routes/api/rooms/index.ts": $api_rooms_index,
    "./routes/api/sendMessage.ts": $api_sendMessage,
    "./routes/api/supabase/textToImage.ts": $api_supabase_textToImage,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Clipboard.tsx": $Clipboard,
    "./islands/Game.tsx": $Game,
    "./islands/Lobby.tsx": $Lobby,
    "./islands/Share.tsx": $Share,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
