// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_room_ from "./routes/[room].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_rooms_index from "./routes/api/rooms/index.ts";
import * as $api_sendMessage from "./routes/api/sendMessage.ts";
import * as $index from "./routes/index.tsx";
import * as $Clipboard from "./islands/Clipboard.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[room].tsx": $_room_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/rooms/index.ts": $api_rooms_index,
    "./routes/api/sendMessage.ts": $api_sendMessage,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Clipboard.tsx": $Clipboard,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
